

export const  GETTODOSLOADING = "GETTODOSLOADING"
export const  GETTODOSSUCCESS = "GETTODOSSUCCESS"
export const  GETTODOSERROR = "GETTODOSERROR"


export const  ADDTODOSLOADING = "ADDTODOSLOADING"
export const  ADDTODOSSUCCESS = "ADDTODOSSUCCESS"
export const  ADDTODOSERROR = "ADDTODOSERROR"



export const  ADDTODO = "ADDTODO"
export const  UPDATETODO = "UPDATETODO"
export const   DELETETODO = "DELETETODO"
export const   COMPLETETODO = "COMPLETETODO"